controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


#app_default: 
#    path: /default
#    controller: App\Controller\DefaultController::index
#    methods:
    
